# .github/workflows/ci.yml
name: CI

on:
  pull_request:
    branches: [main]

env:
  VITE_SUPABASE_URL: http://localhost:54321
  VITE_SUPABASE_ANON_KEY: test_anon_key

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run Vitest
        run: npx vitest run
